Repository DataDog/chef-datadog, pull requests merged in 2018-10, with the labels that each got.

#568 Added index_stats parameter for Elasticsearch config
  .kitchen.yml
  recipes/elasticsearch.rb
  spec/integrations/elasticsearch_spec.rb
  templates/default/elastic.yaml.erb
  test/integration/datadog_elasticsearch/serverspec/elasticsearch_spec.rb
Labels: feature

#560 Use the documented data structure for tags in lighttpd's template.
  templates/default/lighttpd.yaml.erb
Labels: bug

#396 [dd-handler] Bump requirement on `chef_handler`
  .travis.yml
  Rakefile
  metadata.rb
  recipes/dd-handler.rb
Labels: optimize
