Repository DataDog/chef-datadog, pull requests merged in 2018-03, with the labels that each got.

#523 [Amazon Linux] Fix detection of Amazon Linux < 2.0
  providers/monitor.rb
  recipes/dd-agent.rb
  spec/dd-agent_spec.rb
Labels: bug

#520 Force windows_service to restart in order to cope with restart error:
  providers/monitor.rb
  recipes/dd-agent.rb
Labels: bug, windows

#528 [windows] Fix default datadog.yaml template for Windows
  spec/dd-agent_spec.rb
  templates/default/datadog.yaml.erb
Labels: bug, windows

#529 [docs] Update readme, attribute docs for Agent 6
  .kitchen.yml
  README.md
  attributes/default.rb
Labels: documentation

#530 [windows] Update version logic for Agent 6
  .kitchen.yml
  attributes/default.rb
  recipes/_install-windows.rb
  spec/dd-agent_spec.rb
Labels: feature, windows

#508 [handler] Allow configuring `tags_submission_retries` option
  attributes/default.rb
  recipes/dd-handler.rb
  spec/dd-handler_spec.rb
Labels: optimize

#531 Update Agent 6 configuration
  attributes/default.rb
  spec/dd-agent_spec.rb
  templates/default/datadog.yaml.erb
Labels: optimize

#532 [dd-handler] Support passing arbitrary config options to DD handler
  attributes/default.rb
  recipes/dd-handler.rb
  spec/dd-handler_spec.rb
Labels: feature
