Repository DataDog/chef-datadog, pull requests merged in 2019-04, with the labels that each got.

#450 Chef 12.7+ Monitor Resource
  .circleci/config.yml
  .kitchen.yml
  README.md
  metadata.rb
  providers/monitor.rb
  recipes/_install-windows.rb
  resources/monitor.rb
  spec/dd-agent_spec.rb
  spec/dd-handler_spec.rb
  spec/integrations/activemq_spec.rb
  spec/integrations/cassandra_spec.rb
  spec/integrations/couchbase_spec.rb
  spec/integrations/directory_spec.rb
  spec/integrations/disk_spec.rb
  spec/integrations/dns_check_spec.rb
  spec/integrations/docker_daemon_spec.rb
  spec/integrations/elasticsearch_spec.rb
  spec/integrations/etcd_spec.rb
  spec/integrations/go-metro_spec.rb
  spec/integrations/go_expvar_spec.rb
  spec/integrations/gunicorn_spec.rb
  spec/integrations/iis_spec.rb
  spec/integrations/integrations_spec.rb
  spec/integrations/jmx_spec.rb
  spec/integrations/kafka_spec.rb
  spec/integrations/kubernetes_spec.rb
  spec/integrations/mongo_spec.rb
  spec/integrations/nginx_spec.rb
  spec/integrations/php_fpm_spec.rb
  spec/integrations/postfix_spec.rb
  spec/integrations/postgres_spec.rb
  spec/integrations/rabbitmq_spec.rb
  spec/integrations/redis_spec.rb
  spec/integrations/snmp_spec.rb
  spec/integrations/solr_spec.rb
  spec/integrations/sqlserver_spec.rb
  spec/integrations/system_core_spec.rb
  spec/integrations/system_swap_spec.rb
  spec/integrations/tokumx_spec.rb
  spec/integrations/win32_event_log_spec.rb
  spec/integrations/windows_service_spec.rb
  spec/integrations/wmi_check_spec.rb
Labels: feature, ready

#582 Add support for 'site' option.
  attributes/default.rb
  recipes/_agent6_config.rb
  recipes/dd-agent.rb
  recipes/dd-handler.rb
  spec/dd-agent_spec.rb
  templates/default/datadog.yaml.erb
Labels: feature

#596 datadog_monitor doesn't automatically restart the Agent
  README.md
  recipes/activemq.rb
  recipes/apache.rb
  recipes/cacti.rb
  recipes/cassandra.rb
  recipes/consul.rb
  recipes/couchbase.rb
  recipes/couchdb.rb
  recipes/directory.rb
  recipes/disk.rb
  recipes/dns_check.rb
  recipes/docker.rb
  recipes/docker_daemon.rb
  recipes/elasticsearch.rb
  recipes/etcd.rb
  recipes/fluentd.rb
  recipes/go-metro.rb
  recipes/go_expvar.rb
  recipes/gunicorn.rb
  recipes/haproxy.rb
  recipes/hdfs.rb
  recipes/http_check.rb
  recipes/iis.rb
  recipes/integrations.rb
  recipes/jenkins.rb
  recipes/jmx.rb
  recipes/kafka.rb
  recipes/kafka_consumer.rb
  recipes/kubernetes.rb
  recipes/kyototycoon.rb
  recipes/lighttpd.rb
  recipes/memcache.rb
  recipes/mesos.rb
  recipes/mongo.rb
  recipes/mysql.rb
  recipes/network.rb
  recipes/nginx.rb
  recipes/ntp.rb
  recipes/pgbouncer.rb
  recipes/php_fpm.rb
  recipes/postfix.rb
  recipes/postgres.rb
  recipes/process.rb
  recipes/rabbitmq.rb
  recipes/redisdb.rb
  recipes/riak.rb
  recipes/snmp.rb
  recipes/solr.rb
  recipes/sqlserver.rb
  recipes/ssh_check.rb
  recipes/supervisord.rb
  recipes/tcp_check.rb
  recipes/tokumx.rb
  recipes/tomcat.rb
  recipes/varnish.rb
  recipes/vault.rb
  recipes/win32_event_log.rb
  recipes/windows_service.rb
  recipes/wmi_check.rb
  recipes/zookeeper.rb
Labels: ready

#597 Removes the include_recipe chef_handler call from dd-handler
  README.md
  recipes/dd-handler.rb
  spec/dd-handler_spec.rb
Labels: ready

#599 Drops Agent v4 compatibility code.
  attributes/default.rb
  recipes/_install-linux.rb
  spec/dd-agent_spec.rb
Labels: ready

#562 add support for setting max_detailed_exchanges for RabbitMQ
  templates/default/rabbitmq.yaml.erb
Labels: ready
